version: '2'
services:
  web:
    image: flask-hello
    restart: always 
    build: ./web
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    depends_on:
    - redis
    command: gunicorn -b :5000 wsgi:app
  redis: 
    image: redis
  nginx: 
    image: flask-nginx
    restart: always
    build: ./nginx
    ports: 
    - "80:80"
    depends_on: 
    - web