version: '3.7'
services:
  web:
    image: rongying/flask-hello
    restart: always 
    build: ./web
    ports:
    - "5000:5000"
    deploy: 
      replicas: 2
      restart_policy: 
        condition: on-failure 
    depends_on:
    - redis
    command: gunicorn -b :5000 wsgi:app
  redis: 
    image: redis
  nginx: 
    image: rongying/flask-nginx
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure 
    build: ./nginx
    ports: 
    - "80:80"
    depends_on: 
    - web